server:
  port: 8888

logging:
  level:
    com.longyi.bikescreen: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bikescreen?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
    http:
      multipart:
        enabled=true